export const ActionTypes = {
  GET_ALL_POSTS_REQUEST: "GET_ALL_POSTS_REQUEST",
  GET_ALL_POSTS_SUCCESS: "GET_ALL_POSTS_SUCCESS",
  GET_ALL_POSTS_FAILURE: "GET_ALL_POSTS_FAILURE",
  
  CREATE_NEW_POST_REQUEST: "CREATE_NEW_POST_REQUEST",
  CREAT_NEW_POST_SUCCEST: "CREATE_NEW_POST_SUCCESS",
  CREATE_NEW_POST_FAILURE: "CREATE_NEW_POST_FAILURE",

  CREATE_USER: "CREATE_USER",
};
