export const ActionTypes = {
  GET_ALL_POSTS_REQUEST: "GET_ALL_POSTS_REQUEST",
  GET_ALL_POSTS_SUCCESS: "GET_ALL_POSTS_SUCCESS",
  GET_ALL_POSTS_FAILURE: "GET_ALL_POSTS_FAILURE",

  CREATE_NEW_POST_REQUEST: "CREATE_NEW_POST_REQUEST",
  CREAT_NEW_POST_SUCCEST: "CREATE_NEW_POST_SUCCESS",
  CREATE_NEW_POST_FAILURE: "CREATE_NEW_POST_FAILURE",
  CREATE_USER: "CREATE_USER",

  CONNECT_ROOM_SUCCESS: "CONNECT_ROOM_SUCCESS",
  DISCONNECT_ROOM: "DISCONNECT_ROOM_SUCCESS",
  ADD_USER_TO_ROOM: "ADD_USER_TO_ROOM",
  REMOVE_USER_FROM_ROOM: "REMOVE_USER_FROM_ROOM",
  USER_CHANGE_ROOM: "USER_CHANGE_ROOM",


  INCOMING_PEER_CONNECTION_P2P: "INCOMING_PEER_CONNECTION_P2P",
  INCOMING_DC_CONNECTION_P2P: "INCOMING_DC_CONNECTION_P2P",
  INCOMING_DC_CONNECTION_ERROR: "INCOMING_DC_CONNECTION_ERROR",
  OUTGOING_DC_CONNECTION: "OUTGOING_DC_CONNECTION",
  OUTGOING_DC_CONNECTION_ERROR: "OUTGOING_DC_CONNECTION_ERROR",
  OUTGOING_PEER_CONNECTION: "OUTGOING_PEER_CONNECTION",
  DISCONNECTED: "DISCONNECTED",

  FILE_RECEIVED: "FILE_RECEIVED",
  INFO: "INFO",
  FILE_CANCELED: "FILE_CANCELED",

  RESPONSE: "RESPONSE",
  FILE_SENT: "FILE_SENT",

  SEARCH_USER_REQUEST: "SEARCH_USER_REQUEST",
  SEARCH_USER_SUCCESS: "SEARCH_USER_SUCCESS",
  SEARCH_USER_FAILURE: "SEARCH_USER_FAILURE",
  CONNECTED_ROOM: "CONNECTED_ROOM",
  USER_ADDED_ROOM: "USER_ADDED_ROOM",
  USER_REMOVED_ROOM: "USER_REMOVED_ROOM",
  DISCONNECTED_ROOM: "DISCONNECTED_ROOM",
  USER_CHANGED: "USER_CHANGED",

  SET_USER_STATUS: "SET_CONNECTION_STATUS",
  SET_FILE_INFO: "SET_FILE_INFO",
  SET_RECEIVED: "SET_RECEIVED",
  SET_SENT: "SET_SENT",
  SET_DOWNLOAD_LINK: "SET_DOWNLOAD_LINK",
  SET_FILE: "SET_FILE",
  SET_RECEIVED_FILES: "SET_RECEIVED_FILES",
};
